services:
  - type: web
    name: discord-bot-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health