services:
  - type: web
    name: discord-bot-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health